#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-struts
Version  : 1.3.8
Release  : 2
URL      : https://repo1.maven.org/maven2/org/apache/struts/struts-core/1.3.8/struts-core-1.3.8.jar
Source0  : https://repo1.maven.org/maven2/org/apache/struts/struts-core/1.3.8/struts-core-1.3.8.jar
Source1  : https://repo1.maven.org/maven2/org/apache/struts/struts-core/1.3.8/struts-core-1.3.8.pom
Source2  : https://repo1.maven.org/maven2/org/apache/struts/struts-master/4/struts-master-4.pom
Source3  : https://repo1.maven.org/maven2/org/apache/struts/struts-parent/1.3.8/struts-parent-1.3.8.pom
Source4  : https://repo1.maven.org/maven2/org/apache/struts/struts-taglib/1.3.8/struts-taglib-1.3.8.jar
Source5  : https://repo1.maven.org/maven2/org/apache/struts/struts-taglib/1.3.8/struts-taglib-1.3.8.pom
Source6  : https://repo1.maven.org/maven2/org/apache/struts/struts-tiles/1.3.8/struts-tiles-1.3.8.jar
Source7  : https://repo1.maven.org/maven2/org/apache/struts/struts-tiles/1.3.8/struts-tiles-1.3.8.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-struts-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-struts package.
Group: Data

%description data
data components for the mvn-struts package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/struts/struts-core/1.3.8
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/struts/struts-core/1.3.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/struts/struts-core/1.3.8
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/struts/struts-core/1.3.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/struts/struts-master/4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/struts/struts-master/4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/struts/struts-parent/1.3.8
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/struts/struts-parent/1.3.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/struts/struts-taglib/1.3.8
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/struts/struts-taglib/1.3.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/struts/struts-taglib/1.3.8
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/struts/struts-taglib/1.3.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/struts/struts-tiles/1.3.8
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/struts/struts-tiles/1.3.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/struts/struts-tiles/1.3.8
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/struts/struts-tiles/1.3.8


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/struts/struts-core/1.3.8/struts-core-1.3.8.jar
/usr/share/java/.m2/repository/org/apache/struts/struts-core/1.3.8/struts-core-1.3.8.pom
/usr/share/java/.m2/repository/org/apache/struts/struts-master/4/struts-master-4.pom
/usr/share/java/.m2/repository/org/apache/struts/struts-parent/1.3.8/struts-parent-1.3.8.pom
/usr/share/java/.m2/repository/org/apache/struts/struts-taglib/1.3.8/struts-taglib-1.3.8.jar
/usr/share/java/.m2/repository/org/apache/struts/struts-taglib/1.3.8/struts-taglib-1.3.8.pom
/usr/share/java/.m2/repository/org/apache/struts/struts-tiles/1.3.8/struts-tiles-1.3.8.jar
/usr/share/java/.m2/repository/org/apache/struts/struts-tiles/1.3.8/struts-tiles-1.3.8.pom
